/* ============================================================
   Bookstore - Business Questions
   ============================================================ */
   
-- 1) Total units sold and total revenue
-- This query calculates the total number of books sold and the overall revenue generated by the bookstore. 
  
SELECT 
    SUM(soi.Quantity) AS total_units_sold, 
    SUM(soi.Quantity * soi.Unit_Price) AS total_revenue
FROM
    Sale_Order_Items AS soi;

------------------------------------------------------------------------------------------

-- 2) Top 10 best-selling books
-- This query identifies the 10 books with the highest number of units sold and total revenue, helping to highlight the most popular titles.

SELECT 
    b.Book_ID,
    b.Title,
    SUM(soi.Quantity) AS total_units_sold,
    SUM(soi.Quantity * soi.Unit_Price) AS total_revenue
FROM
    Sale_Order_Items AS soi 
        JOIN
    Book AS b ON b.Book_ID = soi.Book_ID
GROUP BY b.Book_ID , b.Title
ORDER BY total_units_sold DESC , total_revenue DESC
LIMIT 10;


------------------------------------------------------------------------------------------

-- 3) Revenue by genre
-- This query analyzes which genres generate the highest revenue, helping the business understand customer preferences.

SELECT
  g.Genre_Name,
  SUM(soi.Quantity * soi.Unit_Price) AS revenue
  
FROM Sale_Order_Items AS soi

JOIN Book           AS b ON b.Book_ID   = soi.Book_ID
JOIN Genre          AS g ON g.Genre_ID  = b.Genre_ID

GROUP BY g.Genre_Name
ORDER BY revenue DESC;


------------------------------------------------------------------------------------------

-- 4) Revenue by publisher (specific date range)
-- This query measures the revenue generated by each publisher between September 20 and October 9, 2025.

SELECT
  p.Publisher_Name,
  SUM(soi.Quantity * soi.Unit_Price) AS revenue
FROM Sale_Order_Items AS soi
JOIN Sale_Order      AS so ON so.Order_ID    = soi.Order_ID 
JOIN Book            AS b  ON b.Book_ID      = soi.Book_ID
JOIN Publisher       AS p  ON p.Publisher_ID = b.Publisher_ID
WHERE so.Order_Date BETWEEN '2025-09-20' AND '2025-10-09'
GROUP BY p.Publisher_Name
ORDER BY revenue DESC;

------------------------------------------------------------------------------------------

-- 5) Average customer rating
-- This query calculates the overall average rating (from 1 to 5) based on customer survey responses.

SELECT 
  COUNT(Survey_ID) AS Response,
  CONCAT(ROUND(AVG(Rating), 2), ' / 5.0') AS average_rating
FROM Survey_Response;

------------------------------------------------------------------------------------------
    
-- 6) Average percentage of wishlist books purchased
-- This query calculates the average percentage of books purchased that were previously added to customers' wishlists,
-- showing how effectively customer interest converts into actual sales.
  
--------------------------  1º Versão ----------------------------------  
  WITH wish AS (
  SELECT 
    c.Customer_ID,
    COUNT(DISTINCT w.Book_ID) AS wishlist_items
  FROM Customer c
  LEFT JOIN Wishlist w 
         ON w.Customer_ID = c.Customer_ID
  GROUP BY c.Customer_ID
),
purchased AS (
  SELECT
    w.Customer_ID,
    COUNT(DISTINCT w.Book_ID) AS wishlist_items_purchased
  FROM Wishlist w
  JOIN Sale_Order so        ON so.Customer_ID = w.Customer_ID
  JOIN Sale_Order_Items soi ON soi.Order_ID   = so.Order_ID
                           AND soi.Book_ID    = w.Book_ID
  GROUP BY w.Customer_ID
),
per_customer AS (
  SELECT
    c.Customer_ID,
    IFNULL(p.wishlist_items_purchased, 0) AS wishlist_items_purchased,
    IFNULL(w.wishlist_items, 0)           AS wishlist_items
  FROM Customer c
  LEFT JOIN wish w      ON w.Customer_ID = c.Customer_ID
  LEFT JOIN purchased p ON p.Customer_ID = c.Customer_ID
)
SELECT
  -- SUM(CASE WHEN pc.wishlist_items > 0 THEN 1 ELSE 0 END)                       AS customers_with_wishlist,
  -- SUM(pc.wishlist_items)                                                       AS total_wishlist_items,
  -- SUM(pc.wishlist_items_purchased)                                             AS total_wishlist_items_purchased,
  CONCAT(ROUND(100 * AVG(CASE WHEN pc.wishlist_items > 0 
                 THEN pc.wishlist_items_purchased / pc.wishlist_items END), 2), '%') AS avg_items_purchased_wishlist
FROM per_customer pc;


--------------------------  2º Versão ----------------------------------

SELECT
  CONCAT( 
  ROUND( 100 * AVG(
		CASE 
          WHEN pc.wishlist > 0 
          THEN pc.purchased / pc.wishlist
        END), 2), '%') AS avg_items_purchased_wishlist
FROM (
  SELECT 
    c.Customer_ID,
    COUNT(distinct w.Book_ID) AS wishlist,
    SUM(
      CASE 
        WHEN (
          SELECT COUNT(*)
          FROM Sale_Order so 
          JOIN Sale_Order_Items soi 
            ON soi.Order_ID = so.Order_ID AND soi.Book_ID  = w.Book_ID
          WHERE so.Customer_ID = c.Customer_ID
			) THEN 1 ELSE 0
      END) AS purchased
  FROM Customer c
  LEFT JOIN Wishlist w 
         ON w.Customer_ID = c.Customer_ID
  GROUP BY c.Customer_ID
) AS pc;



